server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false
      routes:
        - id: ms-customer_full
          uri: lb://ms-customer
          predicates:
            - Path=/customers/full
          filters:
            - AuthenticationFiltering
            
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/customers/**
            
        - id: h2-console
          uri: lb://ms-customer
          predicates:
            - Path=/h2-console/**

eureka:
  client:
    serviceUrl:        
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG