server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/customers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/